config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [:index, :update]

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  # В корзине имеется множество позиций товара
  # также доступен метод line_items()
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  # позиция товара не сможет существовать без товара и корзины
  # другими словами, если таблица содержит внешние ключи, тогда
  # используем belongs_to
  # также будут доступны методы carts() и products() для объектов LineItem
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
require 'pago'

class Order < ApplicationRecord

  has_many :line_items, dependent: :destroy
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type
    when "Check"
      payment_method = :check
      payment_details[:routing] = pay_type_params[:routing_number]
      payment_details[:account] = pay_type_params[:account_number]
    when "Credit card"
      payment_method = :credit_card
      month, year = pay_type_params[:expiration_date].split(//)
      payment_details[:cc_num] = pay_type_params[:credit_card_number]
      payment_details[:expiration_month] = month
      payment_details[:expiration_year] = year
    when "Purchase order"
      payment_method = :po
      payment_details[:po_num] = pay_type_params[:po_number]
    end

    payment_result = Pago.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details
    )

    if payment_result.succeeded?
      OrderMailer.received(self).deliver_later
    else
      raise payment_result.error
    end
  end
end

app/models/pay_type.rb
class PayType < ApplicationRecord
  def ids
    PayType.all.pluck(:id)
  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be a URL for GIF, JPG or PNG image"
  }

  private
  # убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/support_request.rb
class SupportRequest < ApplicationRecord
  belongs_to :order, optional: true

  has_rich_text :response
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  class Error < StandardError
  end

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_cart, only: %i[ show edit update destroy ]

  # Оператор rescue_from перехватывает исключение, выданное Cart.find().
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is currently empty" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

  def invalid_cart
    #Свойство logger есть у каждого контроллера. В данном случае мы используем его для записи сообщения в регистрационный уровень error
    logger.error "Attempt to access invalid cart #{params[:id]}"
    # Переадресовываем запрос на отображение каталога, используя метод redirect_to().
    # Аргумент :notice определяет сообщение, которое будет сохранено во флэш-области
    # в качестве уведомления. А зачем нам переадресация, если можно просто отобразить
    # каталог? Если мы применим переадресацию, в браузере будет выставлен URL-адрес
    # магазина, а не http://.../cart/wibble. Таким образом, мы выставляем напоказ
    # меньшую часть нашего приложения, а также оберегаем пользователя от повторного
    # инициирования ошибки в случае перезагрузки страницы
    redirect_to store_index_url, notice: 'Invalid cart'
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  include CurrentCart
  before_action :set_cart
  def index
    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale])
    else
      @products = Product.order(:title)
    end

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
      render record
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/index.html.slim
h1 Welcome
p It's #{Time.now.strftime("%d.%m.%y %H:%M:%S")}
p We have #{pluralize(@total_orders, "order")}

app/views/layouts/application.html.slim
doctype html
head
  title Pragprog Books Online Store
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  script type="text/javascript"
    |I18n.defaultLocale = "#{ I18n.default_locale }";
    |I18n.locale = "#{ I18n.locale }";

  = javascript_pack_tag 'locale_switcher', 'data-turbolinks-track': 'reload'

body
header.main
  aside
    = form_tag store_index_path, class: 'locale' do
      = select_tag 'set_locale',
                     options_for_select(LANGUAGES, I18n.locale.to_s),
                     onchange: 'this.form.submit()'
      = submit_tag 'submit', id: "submit_locale_change"
  = image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'
  h1 = @page_title

section.content
  nav.side_nav
    - if @cart
      .carts#cart
        = render_if @cart && @cart.line_items.any?, @cart
    ul
      li: a href="/" = t('.home')
      li: a href="/questions" = t('.questions')
      li: a href="/news" = t('.news')
      li: a href="/contact" = t('.contact')

    - if session[:user_id]
      nav.logged_in_nav
        ul
          li = link_to 'Orders', orders_path
          li = link_to 'Products', products_path
          li = link_to 'Users', users_path
          li = button_to 'Logout', logout_path, method: :delete
    - else
      nav.logged_in_nav
        ul
          li = link_to 'Login', login_path
  main class = controller.controller_name
    = yield